25/02/2022 05:13:56-INFO-simpleSock.py-61 l2_socket established
25/02/2022 05:13:56-WARNING-simpleSock.py-89 True
25/02/2022 05:14:13-WARNING-simpleSock.py-107 57
25/02/2022 05:14:13-WARNING-simpleSock.py-108 ['', '01', '05', '10', '15']
25/02/2022 05:14:13-WARNING-simpleSock.py-109 0:00:00.076381
25/02/2022 05:14:14-WARNING-simpleSock.py-107 57
25/02/2022 05:14:14-WARNING-simpleSock.py-108 ['', '01', '02', '07', '11']
25/02/2022 05:14:14-WARNING-simpleSock.py-109 0:00:00.100563
Traceback (most recent call last):
  File "/home/wifi/Downloads/simple/Idea-validation-ip-ccn/simpleSock.py", line 94, in <module>
    _rcvPkt = l2_sock.recv(123)
OSError: [Errno 100] Network is down
